package projecteuler.problems;

/**
 * @author Luke Knight
 */

/*
 * Problem 2:
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
 * 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence
 * whose values do not exceed four million, find the sum of the even-valued
 * terms.
 */

public class Problem2 {

	public static int fibonacci(int a, int b) {
		// add first two numbers
		int c = b + a;
		// if a value exceeds four million, stop.
		if (b > 4000000) {
			return 0;
		}
		if (b % 2 == 0) {
			// add even number
			return b + fibonacci(b, c);
		} else {
			// discard odd number
			return 0 + fibonacci(b, c);
		}
	}

	public static void main(String[] args) {

		System.out.println(fibonacci(1, 2));

	}

}
